=== CHIRDL-Openmrs-Modules/dss/api/src/test/resources/dbunitFiles/tableSetupDTD.dtd
<!ELEMENT dataset (
    person*,
    role*,
    users*,
    global_property*,
    dss_rule*,
    dss_rule_type*,
    dss_rule_entry*)>
    
<!ELEMENT person EMPTY>
<!ATTLIST person
    person_id CDATA #REQUIRED
    gender CDATA #IMPLIED
    birthdate CDATA #IMPLIED
    birthdate_estimated CDATA #IMPLIED
    dead CDATA #REQUIRED
    death_date CDATA #IMPLIED
    cause_of_death CDATA #IMPLIED
    creator CDATA #IMPLIED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    voided CDATA #REQUIRED
    voided_by CDATA #IMPLIED
    date_voided CDATA #IMPLIED
    void_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
    deathdate_estimated CDATA #REQUIRED
    birthtime CDATE #IMPLIED
>

<!ELEMENT role EMPTY>
<!ATTLIST role
    role CDATA #REQUIRED
    description CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id CDATA #REQUIRED
    system_id CDATA #REQUIRED
    username CDATA #IMPLIED
    password CDATA #IMPLIED
    salt CDATA #IMPLIED
    secret_question CDATA #IMPLIED
    secret_answer CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    person_id CDATA #REQUIRED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT dss_rule EMPTY>
<!ATTLIST dss_rule
    rule_id CDATA #REQUIRED
    class_filename CDATA #REQUIRED
    creation_time CDATA #REQUIRED
    title CDATA #IMPLIED
    version CDATA #IMPLIED
    institution CDATA #IMPLIED
    author CDATA #IMPLIED
    specialist CDATA #IMPLIED
    ruleCreationDate CDATA #IMPLIED
    purpose CDATA #IMPLIED
    explanation CDATA #IMPLIED
    keywords CDATA #IMPLIED
    citations CDATA #IMPLIED
    links CDATA #IMPLIED
    data CDATA #IMPLIED
    logic CDATA #IMPLIED
    action CDATA #IMPLIED
    last_modified CDATA #IMPLIED
    token_name CDATA #IMPLIED
    age_min_units CDATA #IMPLIED
    age_max_units CDATA #IMPLIED
    age_min CDATA #IMPLIED
    age_max CDATA #IMPLIED
>

<!ELEMENT dss_rule_entry EMPTY>
<!ATTLIST dss_rule_entry
    rule_entry_id CDATA #REQUIRED
    rule_type_id CDATA #REQUIRED
    rule_id CDATA #REQUIRED
    priority CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT dss_rule_type EMPTY>
<!ATTLIST dss_rule_type
    rule_type_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    creator CDATA #REQUIRED
    date_created CDATA #REQUIRED
    changed_by CDATA #IMPLIED
    date_changed CDATA #IMPLIED
    retired CDATA #REQUIRED
    retired_by CDATA #IMPLIED
    date_retired CDATA #IMPLIED
    retire_reason CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

<!ELEMENT global_property EMPTY>
<!ATTLIST global_property
    property CDATA #REQUIRED
    property_value CDATA #IMPLIED
    description CDATA #IMPLIED
    uuid CDATA #REQUIRED
>

=== CHIRDL-Openmrs-Modules/dss/api/src/test/resources/dbunitFiles/tableSetup.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "tableSetupDTD.dtd">
<dataset>
    <person person_id="1" gender="" birthdate="1975-06-30" birthdate_estimated="false" dead="false" date_created="2005-01-01 00:00:00.0" voided="false" uuid="6adb7c42-cfd2-4301-b53b-ff17c5654ff7"/>
    <role role="Anonymous" description="Everyone and their brother should have this role" uuid="5b773b4d-90be-4d3f-81ca-cbb1441541ec"/>
    <role role="Authenticated" description="Every person logged in automatically has this role." uuid="0dc8933e-7105-4c3b-b86c-15618d854660"/>
    <role role="System Developer" description="Administrators of the OpenMRS .. have additional access to change fundamental structure of the database model." uuid="0e43640b-67d1-4458-b47f-b64fd8ce4b0d"/>
    <users user_id="1" person_id="1" system_id="1-8" username="admin" password="4a1750c8607d0fa237de36c6305715c223415189" salt="c788c6ad82a157b712392ca695dfcf2eed193d7f" secret_question="" creator="1" date_created="2005-01-01 00:00:00.0" changed_by="1" date_changed="2007-09-20 21:54:12.0" retired="false" retire_reason="" uuid="1010d442-e134-11de-babe-001e378eb67e"/>
	<global_property property="dss.ruleSortOrder" property_value="ASC" description="Order rules should be sorted when retrieved from the database. ASC - ascending, DESC - descending" uuid="a8607fc0-f273-11e0-be21-005056956394"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/MDEPFUPWS.class" rule_id="3" creation_time="2009-01-07 13:17:52" title="Depression Maternal Depression PWS Followup" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Prompts MD to follow up suspected maternal depression. Checks if parent has gotten mental health treatment or is no longer depressed." explanation="This prompt is fired if MD concluded on PWS parent may have depression." keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="MDEPFUPWS" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule1.class" rule_id="4" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 1" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule1" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule2.class" rule_id="5" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 2" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule2" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule3.class" rule_id="6" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 3" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule3" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule4.class" rule_id="7" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 4" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule4" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule class_filename="F:\chica\ruleClassDirectory/org/openmrs/module/chica/rule/PrioritizedRule5.class" rule_id="8" creation_time="2009-01-07 13:17:52" title="Prioritized Rule 5" version="1" institution="Indiana University School of Medicine" author="The author" specialist="Pediatrics" ruleCreationDate="2004-07-28 05:16:59" purpose="Test purpose" explanation="Test explanation" keywords="depression, PWS, study, maternal, mom" citations="This is a citation" links="This is a link" data="read read read read read read read If endif" logic="If If conclude If conclude Else conclude endif If If || If || If || If || If || If || If || If || If CALL endif If CALL CALL endif If CALL endif If CALL CALL endif If CALL CALL endif If CALL CALL endif If CALL endif endif" action="write write write write write write write" last_modified="2016-03-22 10:21:18" token_name="PriorizedRule5" age_min_units="days" age_max_units="months" age_min="0" age_max="27"/>
    <dss_rule_type rule_type_id="1" name="PWS" creator="1" date_created="2017-07-19 11:32:21" retired="0" uuid="7cb211ff-6c97-11e7-9be2-0a0027000019"/>
    <dss_rule_type rule_type_id="2" name="PWS_2" creator="1" date_created="2017-08-20 11:32:21" retired="0" uuid="7cb211ff-6c97-11e7-9be2-0a0027000018"/>
    <dss_rule_type rule_type_id="3" name="PrioritizedTest" creator="1" date_created="2017-07-19 11:32:21" retired="0" uuid="7cb211ff-6c97-11e7-9be2-0a0027000020"/>
    <dss_rule_type rule_type_id="4" name="RetiredTest" creator="1" date_created="2017-07-19 11:32:21" retired="1" retired_by="1" retire_reason="testing" uuid="7cb211ff-6c97-11e7-9be2-0a0027000021"/>
    <dss_rule_entry rule_entry_id="1" rule_type_id="1" rule_id="3" priority="227" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000010"/>
    <dss_rule_entry rule_entry_id="2" rule_type_id="3" rule_id="4" priority="222" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000011"/>
    <dss_rule_entry rule_entry_id="3" rule_type_id="3" rule_id="5" priority="220" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000012"/>
    <dss_rule_entry rule_entry_id="4" rule_type_id="3" rule_id="6" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000013"/>
    <dss_rule_entry rule_entry_id="5" rule_type_id="3" rule_id="7" priority="223" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000014"/>
    <dss_rule_entry rule_entry_id="6" rule_type_id="2" rule_id="7" priority="223" creator="1" date_created="2017-07-19 11:34:46" retired="0" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000015"/>
    <dss_rule_entry rule_entry_id="7" rule_type_id="3" rule_id="8" priority="223" creator="1" date_created="2017-07-19 11:34:46" retired="1" retired_by="1" date_retired="2018-07-19 11:34:46" retire_reason="Test void" uuid="d30cb9c7-6c97-11e7-9be2-0a0027000016"/>
</dataset>
